### ISSUE TITLE
"Keep it simple" is a good principle

### ISSUE THREAD

**Issue by joergent** [sstalle/php7cc#52]
"You may also need composer to install php7cc."
I don't know, what composer is. I don't want to clutter my server by installing utilities only used for a single program to be used for a limited time and wasting time on learning about them and their possible side effects.
That is why I do not use php7cc, but use e.g. php7mar instead.

**Comment by sstalle** [comment]
If you don't want to use composer, you can get a `phar` package from the [releases page](https://github.com/sstalle/php7cc/releases). It can be run like a regular php file:
```php php7cc.phar --help```

**Comment by gisostallenberg** [comment]
@joergent, you can read what [Composer](https://en.wikipedia.org/wiki/Composer_(software)) is at Wikipedia and how it works at [their page](https://getcomposer.org/doc/). It is quite common and used to keep packages small and have a single responsibility. That is part of 'keep it simple' IMO.
Composer can be downloaded and run immediately, no need to 'clutter' anything.
```bash
php -r "readfile('https://getcomposer.org/installer');" | php
```
Now you can run 
```bash
php composer.phar
```
and remove composer.phar when you are done.
As you can see in the README the option --dev is advised. That is because php7cc is not to run on servers, but on development environments.
